* TOOD

tood is a simple curses application for managing a todo list.  This is alpha
quality software and I may never need it to be anything more.

The program needs to run on my phone.  The easiest way to do this is Python
under Termux.

The list is backed on version control (git) and all operations trigger a
commit, so data loss is unlikely.

** Running it

If you're on a normal operating system that installs in accordance with the
FHS, just do

#+BEGIN_SRC sh
  ./tood.py
#+END_SRC

However, Termux doesn't put things there.  Shebangs won't work right because
they require hardcoding paths.  I recommend defining an alias for this:

#+BEGIN_SRC sh
  echo >> ~/.bashrc <<EOF
  function t() {
      cd ~/tood
      python2 tood.py
  }
  EOF
  source ~/.bashrc
#+END_SRC

which, while a lot to type, does mean that you can just run it with a single
letter in the future.

** Files

*** tood.py

This is the main program.  Run this; press =h= or =?= for help.

*** debuglisten.py

This is a simple event listener for curses.  It's useful for determining what
"keys" curses presents in response to various actions.
